name: Sync Issues to Private Repo

on:
  issues:
    types: [opened]

jobs:
  sync_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue in private repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/peteriadamgabor/faypy/issues \
          -d "{\"title\": \"${{ github.event.issue.title }}\", \"body\": \"${{ github.event.issue.body }}\n\nOriginal issue: ${{ github.event.issue.html_url }}\", \"assignees\":[], \"milestone\":null, \"labels\":[]}"
